export default {
  start: [
    {
      ' ': 'KẾT QUẢ KIỂM TRA NĂNG LỰC TIẾNG ANH THEO BÀI THI IELTS (NGHE VÀ ĐỌC) TRÊN MÁY TÍNH',
      __EMPTY: '',
      __EMPTY_1: '',
      __EMPTY_2: '',
      __EMPTY_3: '',
      __EMPTY_4: '',
      __EMPTY_5: '',
      __EMPTY_6: '',
      __EMPTY_7: '',
      __EMPTY_8: '',
      __EMPTY_9: '',
      __EMPTY_10: '',
      __EMPTY_11: '',
      __EMPTY_12: '',
      __EMPTY_13: '',
    },
    {
      ' ': 'Ngày thi: ',
      __EMPTY: '',
      __EMPTY_1: '02/10/2022 đến 12/10/2022',
      __EMPTY_2: '',
      __EMPTY_3: '',
      __EMPTY_4: '',
      __EMPTY_5: '',
      __EMPTY_6: '',
      __EMPTY_7: '',
      __EMPTY_8: '',
      __EMPTY_9: '',
      __EMPTY_10: '',
      __EMPTY_11: '',
      __EMPTY_12: '',
      __EMPTY_13: '',
    },
    {
      ' ': 'Địa điểm thi:',
      __EMPTY: '',
      __EMPTY_1: 'Phòng thi máy Trung tâm Ngoại ngữ Kinh tế (Tầng 2)',
      __EMPTY_2: '',
      __EMPTY_3: '',
      __EMPTY_4: '',
      __EMPTY_5: '',
      __EMPTY_6: '',
      __EMPTY_7: '',
      __EMPTY_8: '',
      __EMPTY_9: '',
      __EMPTY_10: '',
      __EMPTY_11: '',
      __EMPTY_12: '',
      __EMPTY_13: '',
    },
    {
      ' ': 'STT ',
      __EMPTY: 'Mã sinh viên',
      __EMPTY_1: 'Giới tính',
      __EMPTY_2: 'Họ và tên\r\n',
      __EMPTY_3: '',
      __EMPTY_4: 'Năm sinh',
      __EMPTY_5: 'Số CMND/CCCD/Hộ chiếu',
      __EMPTY_6: 'Ngành',
      __EMPTY_7: 'Lớp',
      __EMPTY_8: 'Ngày thi',
      __EMPTY_9: 'Ca thi',
      __EMPTY_10: 'Giờ thi',
      __EMPTY_11: 'Điểm IELTS Đọc',
      __EMPTY_12: 'Điểm IELTS Viết',
      __EMPTY_13: 'Tổng điểm',
    },
    {
      ' ': '',
      __EMPTY: '',
      __EMPTY_1: '',
      __EMPTY_2: 'Họ đệm',
      __EMPTY_3: 'Tên',
      __EMPTY_4: '',
      __EMPTY_5: '',
      __EMPTY_6: '',
      __EMPTY_7: '',
      __EMPTY_8: '',
      __EMPTY_9: '',
      __EMPTY_10: '',
      __EMPTY_11: '',
      __EMPTY_12: '',
      __EMPTY_13: '',
    },
  ],
  end: [
    {
      ' ': 'Danh sách có ... người.\r\n',
      __EMPTY: '',
      __EMPTY_1: '',
      __EMPTY_2: '',
      __EMPTY_3: '',
      __EMPTY_4: '',
      __EMPTY_5: '',
      __EMPTY_6: '',
      __EMPTY_7: '',
      __EMPTY_8: '',
      __EMPTY_9: '',
      __EMPTY_10: '',
      __EMPTY_11: '',
      __EMPTY_12: '',
      __EMPTY_13: '',
    },
    {
      ' ': 'ĐẠI DIỆN TRUNG TÂM NGOẠI NGỮ KINH TẾ',
      __EMPTY: '',
      __EMPTY_1: '',
      __EMPTY_2: '',
      __EMPTY_3: '',
      __EMPTY_4: '',
      __EMPTY_5: '',
      __EMPTY_6: '',
      __EMPTY_7: 'ĐẠI DIỆN TỔ CHỨC GIÁO DỤC IDP VIỆT NAM',
      __EMPTY_8: '',
      __EMPTY_9: '',
      __EMPTY_10: '',
      __EMPTY_11: '',
      __EMPTY_12: '',
      __EMPTY_13: '',
    },
  ],
  row: {
    ' ': '',
    __EMPTY: '',
    __EMPTY_1: '',
    __EMPTY_2: '',
    __EMPTY_3: '',
    __EMPTY_4: '',
    __EMPTY_5: '',
    __EMPTY_6: '',
    __EMPTY_7: '',
    __EMPTY_8: '',
    __EMPTY_9: '',
    __EMPTY_10: '',
    __EMPTY_11: '',
    __EMPTY_12: '',
    __EMPTY_13: '',
  },
  raw: {
    '!ref': 'A1:O84',
    A1: { t: 's', v: ' ', r: '<t xml:space="preserve"> </t>', h: ' ', w: ' ' },
    A2: {
      t: 's',
      v: 'KẾT QUẢ KIỂM TRA NĂNG LỰC TIẾNG ANH THEO BÀI THI IELTS (NGHE VÀ ĐỌC) TRÊN MÁY TÍNH',
      r: '<t>KẾT QUẢ KIỂM TRA NĂNG LỰC TIẾNG ANH THEO BÀI THI IELTS (NGHE VÀ ĐỌC) TRÊN MÁY TÍNH</t>',
      h: 'KẾT QUẢ KIỂM TRA NĂNG LỰC TIẾNG ANH THEO BÀI THI IELTS (NGHE VÀ ĐỌC) TRÊN MÁY TÍNH',
      w: 'KẾT QUẢ KIỂM TRA NĂNG LỰC TIẾNG ANH THEO BÀI THI IELTS (NGHE VÀ ĐỌC) TRÊN MÁY TÍNH',
    },
    A4: {
      t: 's',
      v: 'Ngày thi: ',
      r: '<t xml:space="preserve">Ngày thi: </t>',
      h: 'Ngày thi: ',
      w: 'Ngày thi: ',
    },
    C4: {
      t: 's',
      v: '02/10/2022 đến 12/10/2022',
      r: '<t>02/10/2022 đến 12/10/2022</t>',
      h: '02/10/2022 đến 12/10/2022',
      w: '02/10/2022 đến 12/10/2022',
    },
    A5: {
      t: 's',
      v: 'Địa điểm thi:',
      r: '<t>Địa điểm thi:</t>',
      h: 'Địa điểm thi:',
      w: 'Địa điểm thi:',
    },
    C5: {
      t: 's',
      v: 'Phòng thi máy Trung tâm Ngoại ngữ Kinh tế (Tầng 2)',
      r: '<t>Phòng thi máy Trung tâm Ngoại ngữ Kinh tế (Tầng 2)</t>',
      h: 'Phòng thi máy Trung tâm Ngoại ngữ Kinh tế (Tầng 2)',
      w: 'Phòng thi máy Trung tâm Ngoại ngữ Kinh tế (Tầng 2)',
    },
    A7: {
      t: 's',
      v: 'STT ',
      r: '<t xml:space="preserve">STT </t>',
      h: 'STT ',
      w: 'STT ',
    },
    B7: {
      t: 's',
      v: 'Mã sinh viên',
      r: '<t>Mã sinh viên</t>',
      h: 'Mã sinh viên',
      w: 'Mã sinh viên',
    },
    C7: {
      t: 's',
      v: 'Giới tính',
      r: '<t>Giới tính</t>',
      h: 'Giới tính',
      w: 'Giới tính',
    },
    D7: {
      t: 's',
      v: 'Họ và tên\r\n',
      r: '<t xml:space="preserve">Họ và tên\r\n</t>',
      h: 'Họ và tên&#x000d;<br/>',
      w: 'Họ và tên\r\n',
    },
    F7: {
      t: 's',
      v: 'Năm sinh',
      r: '<t>Năm sinh</t>',
      h: 'Năm sinh',
      w: 'Năm sinh',
    },
    G7: {
      t: 's',
      v: 'Số CMND/CCCD/Hộ chiếu',
      r: '<t>Số CMND/CCCD/Hộ chiếu</t>',
      h: 'Số CMND/CCCD/Hộ chiếu',
      w: 'Số CMND/CCCD/Hộ chiếu',
    },
    H7: { t: 's', v: 'Ngành', r: '<t>Ngành</t>', h: 'Ngành', w: 'Ngành' },
    I7: { t: 's', v: 'Lớp', r: '<t>Lớp</t>', h: 'Lớp', w: 'Lớp' },
    J7: {
      t: 's',
      v: 'Ngày thi',
      r: '<t>Ngày thi</t>',
      h: 'Ngày thi',
      w: 'Ngày thi',
    },
    K7: { t: 's', v: 'Ca thi', r: '<t>Ca thi</t>', h: 'Ca thi', w: 'Ca thi' },
    L7: {
      t: 's',
      v: 'Giờ thi',
      r: '<t>Giờ thi</t>',
      h: 'Giờ thi',
      w: 'Giờ thi',
    },
    M7: {
      t: 's',
      v: 'Điểm IELTS Đọc',
      r: '<t>Điểm IELTS Đọc</t>',
      h: 'Điểm IELTS Đọc',
      w: 'Điểm IELTS Đọc',
    },
    N7: {
      t: 's',
      v: 'Điểm IELTS Viết',
      r: '<t>Điểm IELTS Viết</t>',
      h: 'Điểm IELTS Viết',
      w: 'Điểm IELTS Viết',
    },
    O7: {
      t: 's',
      v: 'Tổng điểm',
      r: '<t>Tổng điểm</t>',
      h: 'Tổng điểm',
      w: 'Tổng điểm',
    },
    D8: { t: 's', v: 'Họ đệm', r: '<t>Họ đệm</t>', h: 'Họ đệm', w: 'Họ đệm' },
    E8: { t: 's', v: 'Tên', r: '<t>Tên</t>', h: 'Tên', w: 'Tên' },
    A9: { t: 'n', v: 1, w: '1' },
    A10: {
      t: 's',
      v: 'Danh sách có ... người.\r\n',
      r: '<t xml:space="preserve">Danh sách có ... người.\r\n</t>',
      h: 'Danh sách có ... người.&#x000d;<br/>',
      w: 'Danh sách có ... người.\r\n',
    },
    A12: {
      t: 's',
      v: 'ĐẠI DIỆN TRUNG TÂM NGOẠI NGỮ KINH TẾ',
      r: '<t>ĐẠI DIỆN TRUNG TÂM NGOẠI NGỮ KINH TẾ</t>',
      h: 'ĐẠI DIỆN TRUNG TÂM NGOẠI NGỮ KINH TẾ',
      w: 'ĐẠI DIỆN TRUNG TÂM NGOẠI NGỮ KINH TẾ',
    },
    I12: {
      t: 's',
      v: 'ĐẠI DIỆN TỔ CHỨC GIÁO DỤC IDP VIỆT NAM',
      r: '<t>ĐẠI DIỆN TỔ CHỨC GIÁO DỤC IDP VIỆT NAM</t>',
      h: 'ĐẠI DIỆN TỔ CHỨC GIÁO DỤC IDP VIỆT NAM',
      w: 'ĐẠI DIỆN TỔ CHỨC GIÁO DỤC IDP VIỆT NAM',
    },
    '!margins': {
      left: 0.7,
      right: 0.7,
      top: 0.75,
      bottom: 0.75,
      header: 0.3,
      footer: 0.3,
    },
    '!merges': [
      { s: { c: 14, r: 6 }, e: { c: 14, r: 7 } },
      { s: { c: 8, r: 11 }, e: { c: 14, r: 11 } },
      { s: { c: 0, r: 1 }, e: { c: 14, r: 1 } },
      { s: { c: 12, r: 6 }, e: { c: 12, r: 7 } },
      { s: { c: 13, r: 6 }, e: { c: 13, r: 7 } },
      { s: { c: 9, r: 6 }, e: { c: 9, r: 7 } },
      { s: { c: 10, r: 6 }, e: { c: 10, r: 7 } },
      { s: { c: 11, r: 6 }, e: { c: 11, r: 7 } },
      { s: { c: 0, r: 9 }, e: { c: 4, r: 9 } },
      { s: { c: 0, r: 11 }, e: { c: 6, r: 11 } },
      { s: { c: 5, r: 6 }, e: { c: 5, r: 7 } },
      { s: { c: 6, r: 6 }, e: { c: 6, r: 7 } },
      { s: { c: 7, r: 6 }, e: { c: 7, r: 7 } },
      { s: { c: 8, r: 6 }, e: { c: 8, r: 7 } },
      { s: { c: 0, r: 2 }, e: { c: 8, r: 2 } },
      { s: { c: 0, r: 6 }, e: { c: 0, r: 7 } },
      { s: { c: 1, r: 6 }, e: { c: 1, r: 7 } },
      { s: { c: 2, r: 6 }, e: { c: 2, r: 7 } },
      { s: { c: 3, r: 6 }, e: { c: 4, r: 6 } },
      { s: { c: 0, r: 3 }, e: { c: 1, r: 3 } },
      { s: { c: 0, r: 4 }, e: { c: 1, r: 4 } },
    ],
  },
};
