export enum UserType {
  USER = 'USER',
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  TEACHER = 'TEACHER',
  BANNED = 'BANNED',
  //TODO:
  EXAMMANAGEMENT = 'EXAMMANAGEMENT',
  POINTMANAGER = 'POINTMANAGER',
  POETCREATOR = 'POETCREATOR',
  MANAGETESTTAKERS = 'MANAGETESTTAKERS',
}
